input: input.jar
outputPath: output
urlLoad: true
url: http
projectName: NativeProtect
customSuffix: Native
customLoadPackage: native0
clinit_method_name: native_clinit
libPath: libs
useAnnotation: false
include: false
includes: 
 - cc.magicyari.*
 - cc.magicyari.Main
excludes:
 - cc.magicyari.*
 - cc.magicyari.Main
